<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta http-equiv="X-UA-Compatible" content="ie=edge">';
echo '<title>homework</title>';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-3">';
echo '<div class="card">';
echo '<img class="card-img-top" src="https://pbs.twimg.com/media/Djz_LudUYAE61ZB.jpg">';
echo '<div class="card-body">';
echo '<h4 class="card-title">Text</h4>';
echo '<p class="card-text">memo<p>';
echo '</div>';
echo '<div class="card-footer">';
echo 'By Someone';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="card">';
echo '<img class="card-img-top" src="https://pbs.twimg.com/media/Djz_LudUYAE61ZB.jpg">';
echo '<div class="card-body">';
echo '<h4 class="card-title">Text</h4>';
echo '<p class="card-text">memo<p>';
echo '</div>';
echo '<div class="card-footer">';
echo 'By Someone';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="card">';
echo '<img class="card-img-top" src="https://pbs.twimg.com/media/Djz_LudUYAE61ZB.jpg">';
echo '<div class="card-body">';
echo '<h4 class="card-title">Text</h4>';
echo '<p class="card-text">memo<p>';
echo '</div>';
echo '<div class="card-footer">';
echo 'By Someone';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>
